# Generated by Django 4.2.7 on 2023-12-12 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 21, 29, 44, 571968)),
        ),
    ]
