# Generated by Django 4.2.7 on 2023-12-12 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_post_image_post_subtitle_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Mi Fantastico Blog', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 0, 24, 14, 285823)),
        ),
    ]
