# Generated by Django 4.2.7 on 2023-12-14 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_title_tag_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 21, 12, 19, 468204)),
        ),
    ]
