# Generated by Django 4.2.7 on 2023-12-21 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_remove_post_image_post_header_image_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 21, 1, 1, 10, 563271)),
        ),
    ]
