# Generated by Django 4.2.7 on 2023-12-22 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0016_alter_post_body_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 22, 0, 49, 30, 690655)),
        ),
    ]
